services:
  app:
    build: .
    restart: unless-stopped
    container_name: tia
    init: true
    stop_signal: SIGINT #flask require sigint to stop gracefully
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads #to mount
    environment:
      - PYTHONPATH=/app
      - CONDA_DEFAULT_ENV=tiagui-v2
    command: conda run -n tiagui-v2 python app.py